### ISSUE TITLE
PrettyFaces changes the scheme from Https to Http

### ISSUE THREAD

**Issue by benignoms** [ocpsoft/rewrite#257] opened 2018-01-05 14:51 UTC
I'm using PrettyFaces in my project. We recently started using SSL (Https), however, when calling, for example pretty:main-page in a commandlink the https protocol is modified to http. If I used a normal call without pretty: the protocol is not modified. Is there anything I can do to fix this, without needing to wait for the next version?

**Comment by chkal** [comment] 2018-01-05 16:04
Could you share more details about your setup? Which container are you using? Which version of Rewrite/PrettyFaces, etc...

**Comment by benignoms** [comment] 2018-01-05 17:20
[pretty-config.txt](https://github.com/ocpsoft/rewrite/files/1607310/pretty-config.txt)

I'm usign Glassfish 4, but I've tested it on previous versions and it also did not work.
JSF 2.2

Dependencies
<dependency>
            <groupId>org.ocpsoft.rewrite</groupId>
            <artifactId>rewrite-servlet</artifactId>
            <version>3.4.1.Final</version>
        </dependency>
        <dependency>
            <groupId>org.ocpsoft.rewrite</groupId>
            <artifactId>rewrite-config-prettyfaces</artifactId>
            <version>3.4.1.Final</version>
</dependency>

In a commandLink or commandButton, when I click and send the following action: 

_**pretty:visualizar-processo-cliente**_

Url is modified from Https to Http

**Comment by chkal** [comment] 2018-01-06 10:15
Well, this isn't actually a Rewrite issue, but a problem of your container configuration. Let me try to explain what happens in your case.

Rewrite uses the standard Servlet API to send the redirect.

    httpServletResponse.sendRedirect("/foobar");

Please note that the redirect target is relative to the context path of your application. Now the servlet container transforms this to an absolute URL and sends this to the client in the `Location` HTTP header:

    Location: http://some-domain.com/my-app/foobar

So you see that actually it is your container, which is creating the incorrect absolute URL.

AFAIK there are basically two ways to work around this issue:

  * You could configure Glassfish to assume the `https` scheme for the http listeners. AFAIK there is a `scheme` property on the http listener in the latest Glassfish version. See [this issue](https://github.com/javaee/glassfish/issues/15409) for details.
  * If you are using a load balances / reverse proxy, you could rewrite the Location header before sending it back to the requesting client. That should be easy but depends on you load balances setup. If you are using `mod_proxy`, you can use the `ProxyPassReverse` command to achieve this.

**Comment by lincolnthree** [comment] 2022-06-03 13:54
Thanks @benignoms and @chkal - I'm doing some GitHhub cleanup, and closing this issue as "Not a bug." Please feel free to re-open if you disagree!

**Closed by lincolnthree** 2022-06-03 13:54 UTC
