### ISSUE TITLE
NullPointerException in org.ocpsoft.urlbuilder.AddressBuilder#queryDecoded

### ISSUE THREAD

**Issue by rainermueller** [ocpsoft/rewrite#243] opened 2016-08-22 19:23 UTC
Method throws NullPointerException with given input (line 204)
CharSequence name = null
Object... values = Object[0]

Method called from org.ocpsoft.rewrite.servlet.config.PathAndQuery#evaluateHttp (line 133)

InboundRewrite [POST url=http://localhost:8080/rest/authenticationServices/validateUserCredentials, flow=UN_HANDLED, dispatchResource=null]

```
    <dependency>
        <groupId>org.ocpsoft.rewrite</groupId>
        <artifactId>rewrite-servlet</artifactId>
        <version>3.4.1.Final</version>
    </dependency>
    <dependency>
        <groupId>org.ocpsoft.rewrite</groupId>
        <artifactId>rewrite-integration-cdi</artifactId>
        <version>3.4.1.Final</version>
    </dependency>
```

**Comment by lincolnthree** [comment] 2016-08-22 20:24
Hi.

Could you please post a full stack trace? Otherwise we won't be able to figure out what's going wrong here.

Even better, if you could submit a test case or sample app that reproduces the issue we would appreciate it!

Thanks again for reporting,
Lincoln

**Comment by rainermueller** [comment] 2016-08-23 04:52
Some more details, sorry for not mentioning. Upgraded from 2.0.12.Final to 3.4.1.Final, with 2.0.12 there was no problem with the code.

Here the full stack trace
```
Caused by: java.lang.NullPointerException
        at org.ocpsoft.urlbuilder.AddressBuilder.queryDecoded(AddressBuilder.java:204) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
        at org.ocpsoft.urlbuilder.AddressBuilderPath.queryDecoded(AddressBuilderPath.java:58) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
        at org.ocpsoft.rewrite.servlet.config.PathAndQuery.evaluateHttp(PathAndQuery.java:134) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
        at org.ocpsoft.rewrite.servlet.config.HttpCondition.evaluate(HttpCondition.java:44) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
        at org.ocpsoft.rewrite.config.RuleBuilder.evaluate(RuleBuilder.java:156) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
        at org.ocpsoft.rewrite.servlet.impl.DefaultHttpRewriteProvider.rewriteInbound(DefaultHttpRewriteProvider.java:205) [rewrite-servlet-3.4.1.Final.jar:3.4.1.Final]
```

Were able to fix the issue by replacing PathAndQuery.matches with Path.matches as our rewrite rules handles request path values only.

**Comment by lincolnthree** [comment] 2016-09-01 13:23
Hey Rainer,

Thanks for the update. Looks like I probably botched something in the performance refactor that wasn't caught by one of our test cases (obviously.)

I'll take a look at this, but if you could post the rule you built (scrubbed for privacy if possible), that would also be really helpful!

Thanks!

**Comment by rainermueller** [comment] 2016-09-12 07:46
```
    @Override
    public Configuration getConfiguration(ServletContext context) {
        final Set<String> rewritePaths = newHashSet();
        rewritePaths.add("/contextRoot");
        rewritePaths.add("/CordaRedirector/");

        return createFilterRulesFrom(rewritePaths);
    }

    private ConfigurationBuilder createFilterRulesFrom(Set<String> rewritePaths) {
        ConfigurationBuilder configuration = ConfigurationBuilder.begin();
        for (String rewritePath : rewritePaths) {
            String rewritePattern = rewritePath + "{pathsuffix}";

            configuration.addRule()
                    .when(PathAndQuery.matches(rewritePattern))
                    .perform(
                            using(wuiCredentialsProvider, wuiSettingsProvider)
                                    .with(wuiProperties)
                                    .withPathPattern(rewritePattern))
                    .where("pathsuffix").matches(".*");

            LOG.debug("Added WUI rewrite rule: " + rewritePattern);
        }
```

As mentioned before we replaced PathAndQuery.matches with Path.matches

**Comment by rainermueller** [comment] 2016-11-02 09:40
Is there an update on this problem? We have to use PathAndQuery class as Path does not forward URL parameters in our proxy application.

**Comment by rainermueller** [comment] 2016-11-02 10:38
Second parameter of `org.ocpsoft.urlbuilder.AddressBuilderPath#queryDecoded` method is a varargs.
```
public AddressBuilderQuery queryDecoded(CharSequence name, Object... values) {
      return parent.queryDecoded(name, values);
}
```

From `org.ocpsoft.rewrite.servlet.config.PathAndQuery#evaluateHttp` the method is called without the varargs parameter `queryDecoded(event.getInboundAddress().getQuery())`

In `org.ocpsoft.urlbuilder.AddressBuilder#queryDecoded` parameter name is null and values is Object[0]. Calling `name.toString()` is causing the `NullPointerException` at line 204.

**Comment by chkal** [comment] 2016-11-03 05:39
Hey @rainermueller. Thanks a lot for the analysis. Unfortunately I don't have much time ATM to work on Rewrite. Would you be interested to contribute a fix for this? Looks like you are familiar with the root cause of the NPE now and writing a unit test that reproduces this should be easy. Any contribution is highly welcome.

**Closed** 2016-11-15 07:11 UTC
Labels: bug
