### ISSUE TITLE
Child class of HttpConfigurationProvider not called at all

### ISSUE THREAD

**Issue by MarinKacaj** [ocpsoft/rewrite#222] opened 2016-02-11 15:17 UTC
Hello,

I added a child of `HttpConfigurationProvider` to my application and annotated it with `@RewriteConfiguration` as in the basic example. However `getConfiguration` is never called, and neither is `priority`.
I've also tried the suggested META-INF way (after removing the annotation), but I still don't get any results.
Rewrite starts up correctly as shown on the server logs (I get all INFO between RewriteFilter starting up... to Rewrite 2.0.1.2.Final initialized and GlobalParameterProvider).

The version I'm using is 2.0.12.Final.
My AS is Wildfly 9.0.2.Final.
I have no other rewrites.

**Comment by chkal** [comment] 2016-02-12 06:43
Which dependencies did you add to your project?

Could you also post the exact name and path of the META-INF services file? Unfortunately minor typos in the file name or folder could cause that Rewrite doesn't find your provider.

**Comment by MarinKacaj** [comment] 2016-02-12 09:53
This is the dependency:
`<dependency>
     <groupId>org.ocpsoft.rewrite</groupId>
     <artifactId>rewrite-servlet</artifactId>
     <version>2.0.12.Final</version>
 </dependency>`
The path of the file:
<war root>/WEB-INF/services/org.ocpsoft.rewrite.config.ConfigurationProvider

**Comment by chkal** [comment] 2016-02-12 10:56
Is the service file path you mentioned relative to the WAR archive root or relative to the classpath?

In case of Maven you have to use:

    src/main/resources/META-INF/services/org.ocpsoft.rewrite.config.ConfigurationProvider

But NOT:

    src/main/webapp/META-INF/services/org.ocpsoft.rewrite.config.ConfigurationProvider

**Comment by MarinKacaj** [comment] 2016-02-15 10:01
Excuse my late reply.
The path of the config provider file is same as required. However apparently it doesn't make it to the .war file. Have you had such a problem before?

**Comment by chkal** [comment] 2016-02-15 10:57
What do you mean with:

>  it doesn't make it to the .war file

Is the services file in the WAR or not?

**Comment by MarinKacaj** [comment] 2016-02-15 11:12
No, services is not there.

**Comment by chkal** [comment] 2016-02-15 11:20
In this case it is definitely a packaging issue.

If you are using Maven and place the file here:

    src/main/resources/META-INF/services/org.ocpsoft.rewrite.config.ConfigurationProvider

Then it should end up in the WAR archive like this:

    WEB-INF/classes/META-INF/services/org.ocpsoft.rewrite.config.ConfigurationProvider

**Comment by MarinKacaj** [comment] 2016-02-15 11:38
Yes, the file is there. However I keep getting 404. Logs show that my configuration provider is still not getting called.
 

    On Monday, February 15, 2016 12:20 PM, Christian Kaltepoth <notifications@github.com> wrote:
 

 In this case it is definitely a packaging issue.If you are using Maven and place the file here:src/main/resources/META-INF/services/org.ocpsoft.rewrite.config.ConfigurationProvider
Then it should end up in the WAR archive like this:WEB-INF/classes/META-INF/services/org.ocpsoft.rewrite.config.ConfigurationProvider

**Comment by chkal** [comment] 2016-02-15 12:57
In this case set a breakpoint here and see what you are getting:

https://github.com/ocpsoft/rewrite/blob/master/api/src/main/java/org/ocpsoft/rewrite/config/ConfigurationLoader.java#L59

You can also create a minimal sample project that reproduces this issue which I could have a look at.

**Comment by MarinKacaj** [comment] 2016-02-15 14:29
The instance itself has a caches list (`ConfigurationLoader`), with a caches field of a size equal to 1, with no fields to display of its own.
These are a few screenshots:
[http://postimg.org/image/piov6oqyd/](url)
[http://postimg.org/image/tqjnffsdx/](url)
[http://postimg.org/image/c4gu7rqlx/](url)
[http://postimg.org/image/5o7vhoi2d/](url)
[http://postimg.org/image/z4nhk3ofp/](url)
[http://postimg.org/image/n5bzcsiut/](url)
[http://postimg.org/image/oyew1441h/](url)

**Comment by chkal** [comment] 2016-02-15 16:25
The most interesting question is whether you provider shows up in the list of providers.

I cannot see what is wrong with your setup from the screenshots. You could try to reproduce the issue with a sample app that you can share. Or you will have to debug the root cause yourself. Rewrite users the default JDK ServiceLoader mechanism under the hood. So there is no magic happening here.

**Comment by MarinKacaj** [comment] 2016-02-16 13:58
Yes, my provider shows up in the list.
I'll make a sample app by the weekend and try the re-write there.

**Comment by lincolnthree** [comment] 2017-02-07 22:09
Closing as out-of-date.

**Closed by lincolnthree** 2017-02-07 22:09 UTC
Labels: support
