### ISSUE TITLE
Redirect should not assume that we will always need url encode

### ISSUE THREAD

**Issue by matiwinnetou** [ocpsoft/rewrite#226] opened 2016-03-21 11:44 UTC
We found an issue where we already have url encoded parameters and ideally we do not want to encode them twice.

the original url which is causing an issue was this for us:

```
https://localhost:8443/fz/search.html?scopeId=C&lang=de&internalRewrite=true&isSearchRequest=true&vc=Car&dam=0&ms=1900%3B25
```

Our business requirements state that such url should be redirected to http and this work except for double encoding.

We found that Redirect class always has a Transpositions.encodePath() and we would like to disable this. Ok, we created a new class, which does Transpositions.identity() but this is clunky.

Turns out that this is a common scenario supported by apache mod rewrite:

```
http://stackoverflow.com/questions/6520484/mod-rewrite-urlencoding-an-already-urlencoded-querystring-parameter-any-way-to
```

One can simply pass NE flag.

I would be happy to contribute some pull request for this but the question is whether you guys agree with this idea and would then merge this.

My proposal would be to provide another overloaded method which disables this via boolean flag:
   public static Redirect permanent(final String, boolean disableUrlEncode) {
      return new Redirect(location, RedirectType.PERMANENT);
   }

thoughts?

**Comment by chkal** [comment] 2016-03-22 16:57
Could you perhaps share the rule you are using? To be honest, I don't fully understand why you have an already encoded URL as a parameter. And please also note that encoding rules for query and path parameters are different.

**Comment by matiwinnetou** [comment] 2016-03-22 19:19
Sure, I have a url like this:

https://localhost:8443/fz/search.html?scopeId=C&lang=de&internalRewrite=true&isSearchRequest=true&vc=Car&dam=0&ms=1900%3B25

somehow the code sees that as encoded and does not decode this

then when my rewrite rule kicks in, this redirects the user to http version of a page, then everything gets screwed since it is encoded twice.

we end up with:

http://localhost:8181/fz/search.html?scopeId=C&lang=de&internalRewrite=true&isSearchRequest=true&vc=Car&dam=0&ms=1900%253B25

**Comment by matiwinnetou** [comment] 2016-03-22 19:20
code looks like this:

```
package pubse.tomcat.rewrite;

import static pubse.util.MoreStrings.hasText;
import static pubse.util.MoreStrings.removeTrailingSlash;

import java.util.function.Predicate;

import javax.servlet.ServletContext;

import org.ocpsoft.rewrite.config.Configuration;
import org.ocpsoft.rewrite.config.ConfigurationBuilder;
import org.ocpsoft.rewrite.config.Direction;
import org.ocpsoft.rewrite.servlet.config.HttpConfigurationProvider;
import org.ocpsoft.rewrite.servlet.config.Path;
import org.ocpsoft.rewrite.servlet.config.Query;
import org.ocpsoft.rewrite.servlet.config.Redirect;
import org.ocpsoft.rewrite.servlet.config.Scheme;

import pubse.app.Config;
import pubse.ecs.component.PageType;
import pubse.util.ConfigProperties;

/**
 * Handles http and https redirect rules
 */
public class ProtocolRules extends HttpConfigurationProvider {

    private static final String SSP_PATH = ("/" + PageType.SSP.page).toLowerCase();

    private static final ConfigProperties config = Config.fromEnvSysAndFallbackProperties();

    @Override
    public int priority() {
        return 0;
    }

    @Override
    public Configuration getConfiguration(final ServletContext context) {
        return ConfigurationBuilder.begin()
            .addRule()
            .when(Direction.isInbound()
                .and(Scheme.matches("{protocol}"))
                .and(Path.matches("{path}"))
                .and(Query.matches("{query}"))
            )
            .perform(Redirect.temporary(String.format("%s{path}?{query}", getRedirectServerPath(true))))
            .where("protocol").constrainedBy((event, ctx, value) -> "http".equals(value))
            .where("path").matches(".*").constrainedBy((event, ctx, value) -> httpsPredicate().test(value))
            .where("query").constrainedBy((event, ctx, value) -> hasText(value))

            .addRule()
            .when(Direction.isInbound()
                .and(Scheme.matches("{protocol}"))
                .and(Path.matches("{path}"))
            )
            .perform(Redirect.temporary(String.format("%s{path}", getRedirectServerPath(true))))
            .where("protocol").constrainedBy((event, ctx, value) -> "http".equals(value))
            .where("path").matches(".*").constrainedBy((event, ctx, value) -> httpsPredicate().test(value))

            .addRule()
            .when(Direction.isInbound()
                .and(Scheme.matches("{protocol}"))
                .and(Path.matches("{path}"))
                .and(Query.matches("{query}"))
            )
            .perform(Redirect.temporary(String.format("%s{path}?{query}", getRedirectServerPath(false))))
            .where("protocol").constrainedBy((event, ctx, value) -> "https".equals(value))
            .where("path").matches(".*").constrainedBy((event, ctx, value) -> httpPredicate().test(value))
            .where("query").constrainedBy((event, ctx, value) -> hasText(value))

            .addRule()
            .when(Direction.isInbound()
                .and(Scheme.matches("{protocol}"))
                .and(Path.matches("{path}"))
            )
            .perform(Redirect.temporary(String.format("%s{path}", getRedirectServerPath(false))))
            .where("protocol").constrainedBy((event, ctx, value) -> "https".equals(value))
            .where("path").matches(".*").constrainedBy((event, ctx, value) -> httpPredicate().test(value));
    }

    private String getServerPart(final boolean secure) {
        final String propertyName = secure ? "GERMANY.pillar.buyersearch.secure.base.url" : "GERMANY.pillar.buyersearch.base.url";

        return removeTrailingSlash(config.getString(propertyName).get());
    }

    private String getRedirectServerPath(boolean secure) {
        return getServerPart(secure);
    }

    private Predicate<String> httpPredicate() {
        return value -> {
            if (value.toLowerCase().startsWith(SSP_PATH)) { //if this is SSP then pass through
                return false;
            }
            if (value.toLowerCase().startsWith("/static")) { //if this is static call then pass through, we do not know if this is http or https sourced
                return false;
            }

            return true;
        };
    }

    private Predicate<String> httpsPredicate() {
        return value -> value.toLowerCase().startsWith(SSP_PATH); //we DEMAND https for SSP page
    }

}

```

**Comment by matiwinnetou** [comment] 2016-03-22 19:21
also this is very clunky that I have 4 rules, where as ideally I should have two rules, I could not get this to work with two rules.

**Comment by chkal** [comment] 2016-03-23 05:59
Hey @matiwinnetou,

thanks, I think I understand you requirement now. So the problem is that `Redirect.temporary()` expects and plain path and not a path with a query string. That's why `Redirect` assumes it has to perform path encoding.

What I think is also causing problems here is that you are trying to address your use case by capturing all the data in the condition parts by using large matching groups and then add constraints for the actual conditions. That leads to very complicated rules. Especially because you need two rules (query string + no query string).

I just hacked together an alternative approach. I didn't test it yet, but it shows how you can try to implement you requirement in a simpler way which is also much simpler to read. 

See this code:

```java
public class MyConfig extends HttpConfigurationProvider {

  @Override
  public Configuration getConfiguration(ServletContext context) {

    return ConfigurationBuilder.begin()

        // if inbound URL is http but requires https, switch the scheme
        .addRule()
        .when(Direction.isInbound().and(Scheme.matches("http").and(httpsRequired())))
        .perform(switchScheme("https"));

  }

  /**
   * Operations that just changes the scheme and redirects the user to the new URL
   */
  private HttpOperation switchScheme(final String newScheme) {
    return new HttpOperation() {
      @Override
      public void performHttp(HttpServletRewrite event, EvaluationContext context) {

        // just replace the scheme, don't change anything else
        String target = event.getAddress().toString()
            .replaceAll("^https?://", newScheme + "://");

        // there are no parameters in the target URL,
        // so this shouldn't break any encoding
        Redirect.temporary(target).perform(event, context);
        
        // if the redirect shown above doesn't work, 
        // you can also do something like this:
        // event.getResponse().sendRedirect(target);
        // Lifecycle.abort().perform(event, context);

      }
    };
  }

  /**
   * Rewrite condition to match URLs that need secure connections
   */
  private Condition httpsRequired() {
    return new HttpCondition() {
      @Override
      public boolean evaluateHttp(HttpServletRewrite event, EvaluationContext context) {

        String path = event.getAddress().getPath();

        // you will have to implement your specific logic here
        return path.contains("/secure/");

      }
    };
  }

  @Override
  public int priority() {
    return 0;
  }
}
```

I hope this helps a bit. Don't be afraid to create custom conditions and rules. It's actually very simple.

And by the way. This code is still JDK7. It will be much simpler if you use JDK8 lambdas.

**Comment by matiwinnetou** [comment] 2016-03-23 07:37
@chkal Thx Christian, I will give it a try!!!

**Comment by chkal** [comment] 2016-07-17 07:07
Hey! Did my suggestion work for you? I'm curious! ;-)

**Comment by lincolnthree** [comment] 2017-02-07 22:08
Closing as out-of-date. Thanks for the elegant solution, @chkal !

**Closed by lincolnthree** 2017-02-07 22:08 UTC

**Comment by matiwinnetou** [comment] 2017-02-08 21:21
Yes it did, sorry that I forgot to close this.

**Comment by lincolnthree** [comment] 2017-02-09 15:16
Great! Thanks for the update and thanks Christian for the great feedback :)
