### ISSUE TITLE
Rewrite 2.0.12 with characters in url + Wildfly 9

### ISSUE THREAD

**Issue by jrry** [ocpsoft/rewrite#220] opened 2016-01-14 21:57 UTC
Hi, I think that I found bug in Rewrite 2.0.12

My pretty-config
```
<pretty-config xmlns="http://ocpsoft.org/schema/rewrite-config-prettyfaces" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="http://ocpsoft.org/schema/rewrite-config-prettyfaces
                      http://ocpsoft.org/xml/ns/prettyfaces/rewrite-config-prettyfaces.xsd">

    <url-mapping id="home">
        <pattern value="/"/>
        <view-id value="/home.xhtml"/>
    </url-mapping>

    <rewrite match="/home.xhtml" substitute="/" redirect="301" />

</pretty-config>
```
When I will add characters "[]" or "{}" to the address... example: "http://localhost:8080/Apptest/["
```
Error processing request
Context Path:/Apptest
Servlet Path:/[
Path Info:null
Query String:null
Stack Trace
javax.servlet.ServletException: Filtered request failed.
```
What's wrong?

**Comment by lincolnthree** [comment] 2016-01-15 04:11
Hey there. Thanks for bringing this to our attention.

Can you try with 3.0.0.Alpha10 and see if you still have this issue? We are working on a new release that has addressed some of the character encoding issues and it's possible that the issue is already resolved, but you may have found something new.

**Comment by lincolnthree** [comment] 2016-01-15 04:11
Additionally, if you could post the entire stack trace, that would also be helpful.

**Comment by jrry** [comment] 2016-01-15 12:46
In 3.0.0.Alpha10 problem with "[" and "]" has been fixed, but with "{" or "}" :-1: 
```
2016-01-15 13:36:05,088 ERROR [io.undertow.request] (default task-38) UT005023: Exception handling request to /Apptest/%7B%7D: javax.servlet.ServletException: Filtered request failed.
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:384)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:72)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:282)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:261)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:80)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:172)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:774)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: No parameter [] was set in the pattern [/Apptest/{}]. Call address.set("", value); or remove the parameter from the pattern.
	at org.ocpsoft.urlbuilder.AddressResult.parameterize(AddressResult.java:185)
	at org.ocpsoft.urlbuilder.AddressResult.parameterize(AddressResult.java:156)
	at org.ocpsoft.urlbuilder.AddressResult.<init>(AddressResult.java:65)
	at org.ocpsoft.urlbuilder.AddressBuilder.build(AddressBuilder.java:64)
	at org.ocpsoft.urlbuilder.AddressBuilderQuery.build(AddressBuilderQuery.java:37)
	at org.ocpsoft.rewrite.servlet.impl.BaseHttpRewrite.getInboundAddress(BaseHttpRewrite.java:93)
	at org.ocpsoft.rewrite.servlet.impl.HttpInboundRewriteImpl.getAddress(HttpInboundRewriteImpl.java:149)
	at org.ocpsoft.rewrite.servlet.impl.HttpInboundRewriteImpl.toString(HttpInboundRewriteImpl.java:155)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.ocpsoft.rewrite.AbstractRewrite.buildLogOutput(AbstractRewrite.java:87)
	at org.ocpsoft.rewrite.AbstractRewrite.logEvaluatedRules(AbstractRewrite.java:68)
	at org.ocpsoft.rewrite.servlet.RewriteFilter.doFilter(RewriteFilter.java:209)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	... 30 more
```

**Comment by chkal** [comment] 2016-01-15 16:50
Yeah, I saw something like this in the past. Basically Rewrite uses `{` and `}` for parameters in URLs. That's why using them is problematic. I don't think that this is easy to fix. :worried:

**Comment by lincolnthree** [comment] 2016-01-15 20:29
Actually, this really shouldn't happen. Rewrite shouldn't attempt to parameterize the URL itself, it should only attempt to parameterize the pattern.

**Comment by lincolnthree** [comment] 2016-01-15 20:45
Ok. I've reproduced this in a test case. Checking it in.

**Comment by lincolnthree** [comment] 2016-01-15 20:49
Also, I believe this is a duplicate of the issue *I* forgot about: https://github.com/ocpsoft/rewrite/issues/195

**Comment by lincolnthree** [comment] 2016-01-15 21:22
This is tricky. I've got it complaining about the actual illegal characters now, but Rewrite really shouldn't blow up on these. It should let the app-server do that if necessary. Looking into it further.

**Comment by lincolnthree** [comment] 2016-01-15 21:25
I think I got it... checking in what I've got for review.

**Comment by lincolnthree** [comment] 2016-01-15 21:28
Almost. Need to update a few Builders.

**Comment by lincolnthree** [comment] 2016-01-15 21:39
Not quite :( Will keep working on it.

**Comment by lincolnthree** [comment] 2016-01-19 17:32
So the current issue I'm facing is that with my latest changes, { and } get dropped from URLs entirely, and I'm not entirely sure why. I believe it's happening in the Java URI class when performing decoding, but I'm not exactly sure what the right solution is. I may try escaping these characters specifically before decoding, but I really don't know if that's correct since they are technically invalid in the URL per specification.

**Comment by lincolnthree** [comment] 2016-01-19 18:18
You can see what I've done so far here: https://github.com/ocpsoft/rewrite/tree/encoding

Essentially I created an AddressBuilder.buildLiteral() that does not attempt to parameterize anything. I think this is an important distinction because when using the AddressBuilder on an inbound URL, you never ever ever want to parameterize, so this effectively lets us turn it off. There's a little bit of code duplication I introduced in order to prototype this that I'll want to remove once it works, but you should be able to get the idea.

Thoughts?

**Comment by chkal** [comment] 2016-01-19 20:13
Hey Lincoln,

I didn't find time to look at the code, but the `AddressBuilder.buildLiteral()` idea sounds great. I also started to work on this some time ago, but wasn't very successful fixing the issue. But I agree that the cause of these problems is the default AddressBuilder API tries to process parameters even for literal URLs.

**Comment by lincolnthree** [comment] 2016-01-19 20:45
Any idea about what the proper behavior of the { and } characters should be in this case? (Or any other "unsupported" characters, for that matter.)

**Comment by chkal** [comment] 2016-01-21 05:27
You mean beside escaping it?

**Comment by seanf** [comment] 2016-02-09 00:32
I have been seeing this problem on outbound URLs too, like `/iteration/view/#{versionHome.projectSlug}/#{versionHome.instance.slug}` which is built by a `navigation-case` in `faces-config.xml`. Both `#{versionHome.projectSlug}` and `#{versionHome.instance.slug}` are EL expressions, and probably shouldn't be interpreted by Rewrite at all. (Currently testing Rewrite 3.0.0.Alpha10 running on JBoss EAP 6.4.5.)

In the meantime, can you suggest any way of working around this please? I would really prefer not to go back to Tuckey UrlRewriteFilter, because this approach is much more elegant.

**Comment by seanf** [comment] 2016-02-09 05:31
> In the meantime, can you suggest any way of working around this please?

Those EL expressions which Rewrite couldn't handle were only there because I forgot to set a `from-outcome` in the `navigation-case`. So my workaround seems to be: fix my navigation rules.

**Comment by lincolnthree** [comment] 2016-07-16 21:50
This is a duplicate of #195, now fixed in the encoding branch, soon to be merged to master.

**Closed by lincolnthree** 2016-07-16 21:50 UTC
Labels: bug
